spring:
  profiles:
    active: dev-security, dev-db-tomcat, @environment.config@
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: true 
      ddl-auto: false
      naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

---

server:
  context-path: /